<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-14T20:04:43 IST" name="Suite" finished-at="2023-06-14T20:05:19 IST" duration-ms="36610">
    <groups>
    </groups>
    <test started-at="2023-06-14T20:04:43 IST" name="Test" finished-at="2023-06-14T20:05:19 IST" duration-ms="36610">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:43 IST" name="beforeMethod" finished-at="2023-06-14T20:04:49 IST" duration-ms="5898" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Verify_Error_on_Incorrect_Credentials()[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:49 IST" name="Verify_Error_on_Incorrect_Credentials" finished-at="2023-06-14T20:04:50 IST" duration-ms="1600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Error_on_Incorrect_Credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:50 IST" name="afterMethod" finished-at="2023-06-14T20:04:51 IST" duration-ms="359" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Error_on_Incorrect_Credentials status=SUCCESS method=LoginTest.Verify_Error_on_Incorrect_Credentials()[pri:0, instance:tests.LoginTest@6069db50] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:51 IST" name="beforeMethod" finished-at="2023-06-14T20:04:55 IST" duration-ms="4066" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Verify_Login_Page_Header()[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:55 IST" name="Verify_Login_Page_Header" finished-at="2023-06-14T20:04:55 IST" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_Page_Header -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:55 IST" name="afterMethod" finished-at="2023-06-14T20:04:55 IST" duration-ms="315" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Login_Page_Header status=SUCCESS method=LoginTest.Verify_Login_Page_Header()[pri:0, instance:tests.LoginTest@6069db50] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:55 IST" name="beforeMethod" finished-at="2023-06-14T20:04:59 IST" duration-ms="4025" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Verify_Username_Field_Present()[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:59 IST" name="Verify_Username_Field_Present" finished-at="2023-06-14T20:04:59 IST" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Username_Field_Present -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@6069db50]" started-at="2023-06-14T20:04:59 IST" name="afterMethod" finished-at="2023-06-14T20:04:59 IST" duration-ms="309" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Username_Field_Present status=SUCCESS method=LoginTest.Verify_Username_Field_Present()[pri:0, instance:tests.LoginTest@6069db50] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.HomePageTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.HomePageTest@4c583ecf]" started-at="2023-06-14T20:04:59 IST" name="beforeMethod" finished-at="2023-06-14T20:05:04 IST" duration-ms="4560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Verify_Links()[pri:0, instance:tests.HomePageTest@4c583ecf]" started-at="2023-06-14T20:05:04 IST" name="Verify_Links" finished-at="2023-06-14T20:05:07 IST" duration-ms="2508" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Leave] but found [Recruitment],
expected [Time] but found [My Info],
expected [Recruitment] but found [Performance],
expected [My Info] but found [Dashboard],
expected [Performance] but found [Directory],
expected [Dashboard] but found [Maintenance],
expected [Directory] but found [Buzz]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Leave] but found [Recruitment],
expected [Time] but found [My Info],
expected [Recruitment] but found [Performance],
expected [My Info] but found [Dashboard],
expected [Performance] but found [Directory],
expected [Dashboard] but found [Maintenance],
expected [Directory] but found [Buzz]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at tests.HomePageTest.Verify_Links(HomePageTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Links -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.HomePageTest@4c583ecf]" started-at="2023-06-14T20:05:07 IST" name="afterMethod" finished-at="2023-06-14T20:05:07 IST" duration-ms="570" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Links status=FAILURE method=HomePageTest.Verify_Links()[pri:0, instance:tests.HomePageTest@4c583ecf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.HomePageTest@4c583ecf]" started-at="2023-06-14T20:05:07 IST" name="beforeMethod" finished-at="2023-06-14T20:05:11 IST" duration-ms="4099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verify_username()[pri:0, instance:tests.HomePageTest@4c583ecf]" started-at="2023-06-14T20:05:11 IST" name="verify_username" finished-at="2023-06-14T20:05:18 IST" duration-ms="7026" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Domina Burndead] but found [VyaWzbEwVJ Collingstestingtestingtesting]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Domina Burndead] but found [VyaWzbEwVJ Collingstestingtestingtesting]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.HomePageTest.verify_username(HomePageTest.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_username -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.HomePageTest@4c583ecf]" started-at="2023-06-14T20:05:19 IST" name="afterMethod" finished-at="2023-06-14T20:05:19 IST" duration-ms="696" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_username status=FAILURE method=HomePageTest.verify_username()[pri:0, instance:tests.HomePageTest@4c583ecf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.HomePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
